spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: tasks
    password: tasks
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
